/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fmod;

public class Channel extends ChannelControl {
  private long swigCPtr;

  protected Channel(long cPtr, boolean cMemoryOwn) {
    super(javafmodJNI.SWIGChannelUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Channel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javafmodJNI.delete_Channel(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

	/** This constructor creates the proxy which initially does not create nor own any C memory */
	public Channel() {
		this(0, false);
	}

  public FMOD_RESULT setFrequency(float frequency) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_setFrequency(swigCPtr, this, frequency));
  }

  public FMOD_RESULT getFrequency(SWIGTYPE_p_float frequency) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_getFrequency(swigCPtr, this, SWIGTYPE_p_float.getCPtr(frequency)));
  }

  public FMOD_RESULT setPriority(int priority) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_setPriority(swigCPtr, this, priority));
  }

  public FMOD_RESULT getPriority(SWIGTYPE_p_int priority) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_getPriority(swigCPtr, this, SWIGTYPE_p_int.getCPtr(priority)));
  }

  public FMOD_RESULT setPosition(long position, long postype) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_setPosition(swigCPtr, this, position, postype));
  }

  public FMOD_RESULT getPosition(SWIGTYPE_p_unsigned_int position, long postype) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_getPosition(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(position), postype));
  }

  public FMOD_RESULT setChannelGroup(ChannelGroup channelgroup) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_setChannelGroup(swigCPtr, this, ChannelGroup.getCPtr(channelgroup), channelgroup));
  }

  public FMOD_RESULT getChannelGroup(ChannelGroup channelgroup) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_getChannelGroup(swigCPtr, this, channelgroup));
  }

  public FMOD_RESULT setLoopCount(int loopcount) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_setLoopCount(swigCPtr, this, loopcount));
  }

  public FMOD_RESULT getLoopCount(SWIGTYPE_p_int loopcount) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_getLoopCount(swigCPtr, this, SWIGTYPE_p_int.getCPtr(loopcount)));
  }

  public FMOD_RESULT setLoopPoints(long loopstart, long loopstarttype, long loopend, long loopendtype) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_setLoopPoints(swigCPtr, this, loopstart, loopstarttype, loopend, loopendtype));
  }

  public FMOD_RESULT getLoopPoints(SWIGTYPE_p_unsigned_int loopstart, long loopstarttype, SWIGTYPE_p_unsigned_int loopend, long loopendtype) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_getLoopPoints(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(loopstart), loopstarttype, SWIGTYPE_p_unsigned_int.getCPtr(loopend), loopendtype));
  }

  public FMOD_RESULT isVirtual(SWIGTYPE_p_bool isvirtual) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_isVirtual(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(isvirtual)));
  }

  public FMOD_RESULT getCurrentSound(Sound sound) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_getCurrentSound(swigCPtr, this, sound));
  }

  public FMOD_RESULT getIndex(SWIGTYPE_p_int index) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Channel_getIndex(swigCPtr, this, SWIGTYPE_p_int.getCPtr(index)));
  }

}
