/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fmod;

public class ChannelGroup extends ChannelControl {
  private long swigCPtr;

  protected ChannelGroup(long cPtr, boolean cMemoryOwn) {
    super(javafmodJNI.SWIGChannelGroupUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javafmodJNI.delete_ChannelGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

	/** This constructor creates the proxy which initially does not create nor own any C memory */
	public ChannelGroup() {
		this(0, false);
	}

  public FMOD_RESULT release() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ChannelGroup_release(swigCPtr, this));
  }

  public FMOD_RESULT addGroup(ChannelGroup group, boolean propagatedspclock, DSPConnection connection) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ChannelGroup_addGroup__SWIG_0(swigCPtr, this, ChannelGroup.getCPtr(group), group, propagatedspclock, connection));
  }

  public FMOD_RESULT addGroup(ChannelGroup group, boolean propagatedspclock) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ChannelGroup_addGroup__SWIG_1(swigCPtr, this, ChannelGroup.getCPtr(group), group, propagatedspclock));
  }

  public FMOD_RESULT addGroup(ChannelGroup group) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ChannelGroup_addGroup__SWIG_2(swigCPtr, this, ChannelGroup.getCPtr(group), group));
  }

  public FMOD_RESULT getNumGroups(SWIGTYPE_p_int numgroups) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ChannelGroup_getNumGroups(swigCPtr, this, SWIGTYPE_p_int.getCPtr(numgroups)));
  }

  public FMOD_RESULT getGroup(int index, ChannelGroup group) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ChannelGroup_getGroup(swigCPtr, this, index, group));
  }

  public FMOD_RESULT getParentGroup(ChannelGroup group) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ChannelGroup_getParentGroup(swigCPtr, this, group));
  }

  public FMOD_RESULT getName(String name, int namelen) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ChannelGroup_getName(swigCPtr, this, name, namelen));
  }

  public FMOD_RESULT getNumChannels(SWIGTYPE_p_int numchannels) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ChannelGroup_getNumChannels(swigCPtr, this, SWIGTYPE_p_int.getCPtr(numchannels)));
  }

  public FMOD_RESULT getChannel(int index, Channel channel) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ChannelGroup_getChannel(swigCPtr, this, index, channel));
  }

}
