/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fmod;

public class CueInstance {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CueInstance(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CueInstance obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javafmodJNI.delete_CueInstance(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

	/** This constructor creates the proxy which initially does not create nor own any C memory */
	public CueInstance() {
		this(0, false);
	}

  public boolean isValid() {
    return javafmodJNI.CueInstance_isValid(swigCPtr, this);
  }

  public FMOD_RESULT trigger() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.CueInstance_trigger(swigCPtr, this));
  }

}
