/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fmod;

public class EventDescription {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EventDescription(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventDescription obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javafmodJNI.delete_EventDescription(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

	/** This constructor creates the proxy which initially does not create nor own any C memory */
	public EventDescription() {
		this(0, false);
	}

  public boolean isValid() {
    return javafmodJNI.EventDescription_isValid(swigCPtr, this);
  }

  public FMOD_RESULT getID(FMOD_GUID id) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getID(swigCPtr, this, FMOD_GUID.getCPtr(id), id));
  }

  public FMOD_RESULT getPath(String path, int size, SWIGTYPE_p_int retrieved) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getPath(swigCPtr, this, path, size, SWIGTYPE_p_int.getCPtr(retrieved)));
  }

  public FMOD_RESULT getParameterCount(SWIGTYPE_p_int count) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getParameterCount(swigCPtr, this, SWIGTYPE_p_int.getCPtr(count)));
  }

  public FMOD_RESULT getParameterByIndex(int index, FMOD_STUDIO_PARAMETER_DESCRIPTION parameter) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getParameterByIndex(swigCPtr, this, index, FMOD_STUDIO_PARAMETER_DESCRIPTION.getCPtr(parameter), parameter));
  }

  public FMOD_RESULT getParameter(String name, FMOD_STUDIO_PARAMETER_DESCRIPTION parameter) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getParameter(swigCPtr, this, name, FMOD_STUDIO_PARAMETER_DESCRIPTION.getCPtr(parameter), parameter));
  }

  public FMOD_RESULT getUserPropertyCount(SWIGTYPE_p_int count) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getUserPropertyCount(swigCPtr, this, SWIGTYPE_p_int.getCPtr(count)));
  }

  public FMOD_RESULT getUserPropertyByIndex(int index, FMOD_STUDIO_USER_PROPERTY property) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getUserPropertyByIndex(swigCPtr, this, index, FMOD_STUDIO_USER_PROPERTY.getCPtr(property), property));
  }

  public FMOD_RESULT getUserProperty(String name, FMOD_STUDIO_USER_PROPERTY property) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getUserProperty(swigCPtr, this, name, FMOD_STUDIO_USER_PROPERTY.getCPtr(property), property));
  }

  public FMOD_RESULT getLength(SWIGTYPE_p_int length) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getLength(swigCPtr, this, SWIGTYPE_p_int.getCPtr(length)));
  }

  public FMOD_RESULT getMinimumDistance(SWIGTYPE_p_float distance) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getMinimumDistance(swigCPtr, this, SWIGTYPE_p_float.getCPtr(distance)));
  }

  public FMOD_RESULT getMaximumDistance(SWIGTYPE_p_float distance) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getMaximumDistance(swigCPtr, this, SWIGTYPE_p_float.getCPtr(distance)));
  }

  public FMOD_RESULT isOneshot(SWIGTYPE_p_bool oneshot) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_isOneshot(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(oneshot)));
  }

  public FMOD_RESULT isStream(SWIGTYPE_p_bool isStream) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_isStream(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(isStream)));
  }

  public FMOD_RESULT is3D(SWIGTYPE_p_bool is3D) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_is3D(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(is3D)));
  }

  public FMOD_RESULT createInstance(EventInstance instance) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_createInstance(swigCPtr, this, instance));
  }

  public FMOD_RESULT getInstanceCount(SWIGTYPE_p_int count) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getInstanceCount(swigCPtr, this, SWIGTYPE_p_int.getCPtr(count)));
  }

  public FMOD_RESULT getInstanceList(EventInstance array, int capacity, SWIGTYPE_p_int count) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getInstanceList(swigCPtr, this, array, capacity, SWIGTYPE_p_int.getCPtr(count)));
  }

  public FMOD_RESULT loadSampleData() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_loadSampleData(swigCPtr, this));
  }

  public FMOD_RESULT unloadSampleData() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_unloadSampleData(swigCPtr, this));
  }

  public FMOD_RESULT getSampleLoadingState(SWIGTYPE_p_FMOD_STUDIO_LOADING_STATE state) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getSampleLoadingState(swigCPtr, this, SWIGTYPE_p_FMOD_STUDIO_LOADING_STATE.getCPtr(state)));
  }

  public FMOD_RESULT releaseAllInstances() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_releaseAllInstances(swigCPtr, this));
  }

  public FMOD_RESULT setCallback(SWIGTYPE_p_f_enum_FMOD_STUDIO_EVENT_CALLBACK_TYPE_p_FMOD_STUDIO_EVENTINSTANCE_p_void__FMOD_RESULT callback) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_setCallback(swigCPtr, this, SWIGTYPE_p_f_enum_FMOD_STUDIO_EVENT_CALLBACK_TYPE_p_FMOD_STUDIO_EVENTINSTANCE_p_void__FMOD_RESULT.getCPtr(callback)));
  }

  public FMOD_RESULT getUserData(SWIGTYPE_p_p_void userData) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_getUserData(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(userData)));
  }

  public FMOD_RESULT setUserData(SWIGTYPE_p_void userData) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.EventDescription_setUserData(swigCPtr, this, SWIGTYPE_p_void.getCPtr(userData)));
  }

}
