/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fmod;

public class FMOD_STUDIO_ADVANCEDSETTINGS {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FMOD_STUDIO_ADVANCEDSETTINGS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_ADVANCEDSETTINGS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javafmodJNI.delete_FMOD_STUDIO_ADVANCEDSETTINGS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static FMOD_STUDIO_ADVANCEDSETTINGS create_and_init() {
    FMOD_STUDIO_ADVANCEDSETTINGS set = new FMOD_STUDIO_ADVANCEDSETTINGS();
    set.init();
    return set;
  }

  public void setCbSize(int value) {
    javafmodJNI.FMOD_STUDIO_ADVANCEDSETTINGS_cbSize_set(swigCPtr, this, value);
  }

  public int getCbSize() {
    return javafmodJNI.FMOD_STUDIO_ADVANCEDSETTINGS_cbSize_get(swigCPtr, this);
  }

  public void setCommandQueueSize(long value) {
    javafmodJNI.FMOD_STUDIO_ADVANCEDSETTINGS_commandQueueSize_set(swigCPtr, this, value);
  }

  public long getCommandQueueSize() {
    return javafmodJNI.FMOD_STUDIO_ADVANCEDSETTINGS_commandQueueSize_get(swigCPtr, this);
  }

  public void setHandleInitialSize(long value) {
    javafmodJNI.FMOD_STUDIO_ADVANCEDSETTINGS_handleInitialSize_set(swigCPtr, this, value);
  }

  public long getHandleInitialSize() {
    return javafmodJNI.FMOD_STUDIO_ADVANCEDSETTINGS_handleInitialSize_get(swigCPtr, this);
  }

  public void init() {
    javafmodJNI.FMOD_STUDIO_ADVANCEDSETTINGS_init(swigCPtr, this);
  }

  public FMOD_STUDIO_ADVANCEDSETTINGS() {
    this(javafmodJNI.new_FMOD_STUDIO_ADVANCEDSETTINGS(), true);
  }

}
