/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fmod;

public class FMOD_STUDIO_USER_PROPERTY {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FMOD_STUDIO_USER_PROPERTY(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_USER_PROPERTY obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javafmodJNI.delete_FMOD_STUDIO_USER_PROPERTY(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    javafmodJNI.FMOD_STUDIO_USER_PROPERTY_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return javafmodJNI.FMOD_STUDIO_USER_PROPERTY_name_get(swigCPtr, this);
  }

  public void setType(FMOD_STUDIO_USER_PROPERTY_TYPE value) {
    javafmodJNI.FMOD_STUDIO_USER_PROPERTY_type_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_STUDIO_USER_PROPERTY_TYPE getType() {
    return FMOD_STUDIO_USER_PROPERTY_TYPE.swigToEnum(javafmodJNI.FMOD_STUDIO_USER_PROPERTY_type_get(swigCPtr, this));
  }

  public FMOD_STUDIO_USER_PROPERTY() {
    this(javafmodJNI.new_FMOD_STUDIO_USER_PROPERTY(), true);
  }

}
