/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fmod;

public class ParameterInstance {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ParameterInstance(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterInstance obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javafmodJNI.delete_ParameterInstance(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

	/** This constructor creates the proxy which initially does not create nor own any C memory */
	public ParameterInstance() {
		this(0, false);
	}

  public boolean isValid() {
    return javafmodJNI.ParameterInstance_isValid(swigCPtr, this);
  }

  public FMOD_RESULT getDescription(FMOD_STUDIO_PARAMETER_DESCRIPTION description) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ParameterInstance_getDescription(swigCPtr, this, FMOD_STUDIO_PARAMETER_DESCRIPTION.getCPtr(description), description));
  }

  public FMOD_RESULT getValue(SWIGTYPE_p_float value) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ParameterInstance_getValue(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value)));
  }

  public FMOD_RESULT setValue(float value) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.ParameterInstance_setValue(swigCPtr, this, value));
  }

}
