/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fmod;

public class Reverb3D {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Reverb3D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Reverb3D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javafmodJNI.delete_Reverb3D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

	/** This constructor creates the proxy which initially does not create nor own any C memory */
	public Reverb3D() {
		this(0, false);
	}

  public FMOD_RESULT release() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Reverb3D_release(swigCPtr, this));
  }

  public FMOD_RESULT set3DAttributes(FMOD_VECTOR position, float mindistance, float maxdistance) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Reverb3D_set3DAttributes(swigCPtr, this, FMOD_VECTOR.getCPtr(position), position, mindistance, maxdistance));
  }

  public FMOD_RESULT get3DAttributes(FMOD_VECTOR position, SWIGTYPE_p_float mindistance, SWIGTYPE_p_float maxdistance) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Reverb3D_get3DAttributes(swigCPtr, this, FMOD_VECTOR.getCPtr(position), position, SWIGTYPE_p_float.getCPtr(mindistance), SWIGTYPE_p_float.getCPtr(maxdistance)));
  }

  public FMOD_RESULT setProperties(FMOD_REVERB_PROPERTIES properties) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Reverb3D_setProperties(swigCPtr, this, FMOD_REVERB_PROPERTIES.getCPtr(properties), properties));
  }

  public FMOD_RESULT getProperties(FMOD_REVERB_PROPERTIES properties) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Reverb3D_getProperties(swigCPtr, this, FMOD_REVERB_PROPERTIES.getCPtr(properties), properties));
  }

  public FMOD_RESULT setActive(boolean active) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Reverb3D_setActive(swigCPtr, this, active));
  }

  public FMOD_RESULT getActive(SWIGTYPE_p_bool active) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Reverb3D_getActive(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(active)));
  }

  public FMOD_RESULT setUserData(SWIGTYPE_p_void userdata) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Reverb3D_setUserData(swigCPtr, this, SWIGTYPE_p_void.getCPtr(userdata)));
  }

  public FMOD_RESULT getUserData(SWIGTYPE_p_p_void userdata) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.Reverb3D_getUserData(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(userdata)));
  }

}
