/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fmod;

public class SoundGroup {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SoundGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SoundGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javafmodJNI.delete_SoundGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

	/** This constructor creates the proxy which initially does not create nor own any C memory */
	public SoundGroup() {
		this(0, false);
	}

  public FMOD_RESULT release() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_release(swigCPtr, this));
  }

  public FMOD_RESULT getSystemObject(FMOD_System system) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_getSystemObject(swigCPtr, this, system));
  }

  public FMOD_RESULT setMaxAudible(int maxaudible) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_setMaxAudible(swigCPtr, this, maxaudible));
  }

  public FMOD_RESULT getMaxAudible(SWIGTYPE_p_int maxaudible) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_getMaxAudible(swigCPtr, this, SWIGTYPE_p_int.getCPtr(maxaudible)));
  }

  public FMOD_RESULT setMaxAudibleBehavior(FMOD_SOUNDGROUP_BEHAVIOR behavior) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_setMaxAudibleBehavior(swigCPtr, this, behavior.swigValue()));
  }

  public FMOD_RESULT getMaxAudibleBehavior(SWIGTYPE_p_FMOD_SOUNDGROUP_BEHAVIOR behavior) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_getMaxAudibleBehavior(swigCPtr, this, SWIGTYPE_p_FMOD_SOUNDGROUP_BEHAVIOR.getCPtr(behavior)));
  }

  public FMOD_RESULT setMuteFadeSpeed(float speed) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_setMuteFadeSpeed(swigCPtr, this, speed));
  }

  public FMOD_RESULT getMuteFadeSpeed(SWIGTYPE_p_float speed) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_getMuteFadeSpeed(swigCPtr, this, SWIGTYPE_p_float.getCPtr(speed)));
  }

  public FMOD_RESULT setVolume(float volume) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_setVolume(swigCPtr, this, volume));
  }

  public FMOD_RESULT getVolume(SWIGTYPE_p_float volume) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_getVolume(swigCPtr, this, SWIGTYPE_p_float.getCPtr(volume)));
  }

  public FMOD_RESULT stop() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_stop(swigCPtr, this));
  }

  public FMOD_RESULT getName(String name, int namelen) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_getName(swigCPtr, this, name, namelen));
  }

  public FMOD_RESULT getNumSounds(SWIGTYPE_p_int numsounds) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_getNumSounds(swigCPtr, this, SWIGTYPE_p_int.getCPtr(numsounds)));
  }

  public FMOD_RESULT getSound(int index, Sound sound) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_getSound(swigCPtr, this, index, sound));
  }

  public FMOD_RESULT getNumPlaying(SWIGTYPE_p_int numplaying) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_getNumPlaying(swigCPtr, this, SWIGTYPE_p_int.getCPtr(numplaying)));
  }

  public FMOD_RESULT setUserData(SWIGTYPE_p_void userdata) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_setUserData(swigCPtr, this, SWIGTYPE_p_void.getCPtr(userdata)));
  }

  public FMOD_RESULT getUserData(SWIGTYPE_p_p_void userdata) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.SoundGroup_getUserData(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(userdata)));
  }

}
