/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fmod;

public class SWIGTYPE_p_p_FMOD__Studio__Bus {
  private long swigCPtr;

  protected SWIGTYPE_p_p_FMOD__Studio__Bus(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_p_FMOD__Studio__Bus() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_p_FMOD__Studio__Bus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

