/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fmod;

public class System {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected System(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(System obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javafmodJNI.delete_System(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

	/** This constructor creates the proxy which initially does not create nor own any C memory */
	public System() {
		this(0, false);
	}

  public static FMOD_RESULT create(System system, long headerVersion) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_create__SWIG_0(system, headerVersion));
  }

  public static FMOD_RESULT create(System system) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_create__SWIG_1(system));
  }

  public FMOD_RESULT setAdvancedSettings(FMOD_STUDIO_ADVANCEDSETTINGS settings) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_setAdvancedSettings(swigCPtr, this, FMOD_STUDIO_ADVANCEDSETTINGS.getCPtr(settings), settings));
  }

  public FMOD_RESULT getAdvancedSettings(FMOD_STUDIO_ADVANCEDSETTINGS settings) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getAdvancedSettings(swigCPtr, this, FMOD_STUDIO_ADVANCEDSETTINGS.getCPtr(settings), settings));
  }

  public FMOD_RESULT initialize(int maxchannels, long studioflags, long flags, SWIGTYPE_p_void extradriverdata) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_initialize(swigCPtr, this, maxchannels, studioflags, flags, SWIGTYPE_p_void.getCPtr(extradriverdata)));
  }

  public FMOD_RESULT release() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_release(swigCPtr, this));
  }

  public boolean isValid() {
    return javafmodJNI.System_isValid(swigCPtr, this);
  }

  public FMOD_RESULT update() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_update(swigCPtr, this));
  }

  public FMOD_RESULT getLowLevelSystem(FMOD_System system) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getLowLevelSystem(swigCPtr, this, system));
  }

  public FMOD_RESULT getEvent(String path, EventDescription event) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getEvent(swigCPtr, this, path, event));
  }

  public FMOD_RESULT getBus(String path, SWIGTYPE_p_p_FMOD__Studio__Bus bus) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getBus(swigCPtr, this, path, SWIGTYPE_p_p_FMOD__Studio__Bus.getCPtr(bus)));
  }

  public FMOD_RESULT getVCA(String path, SWIGTYPE_p_p_FMOD__Studio__VCA vca) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getVCA(swigCPtr, this, path, SWIGTYPE_p_p_FMOD__Studio__VCA.getCPtr(vca)));
  }

  public FMOD_RESULT getBank(String path, Bank bank) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getBank(swigCPtr, this, path, bank));
  }

  public FMOD_RESULT getEventByID(FMOD_GUID id, EventDescription event) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getEventByID(swigCPtr, this, FMOD_GUID.getCPtr(id), id, event));
  }

  public FMOD_RESULT getBusByID(FMOD_GUID id, SWIGTYPE_p_p_FMOD__Studio__Bus bus) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getBusByID(swigCPtr, this, FMOD_GUID.getCPtr(id), id, SWIGTYPE_p_p_FMOD__Studio__Bus.getCPtr(bus)));
  }

  public FMOD_RESULT getVCAByID(FMOD_GUID id, SWIGTYPE_p_p_FMOD__Studio__VCA vca) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getVCAByID(swigCPtr, this, FMOD_GUID.getCPtr(id), id, SWIGTYPE_p_p_FMOD__Studio__VCA.getCPtr(vca)));
  }

  public FMOD_RESULT getBankByID(FMOD_GUID id, Bank bank) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getBankByID(swigCPtr, this, FMOD_GUID.getCPtr(id), id, bank));
  }

  public FMOD_RESULT getSoundInfo(String key, FMOD_STUDIO_SOUND_INFO info) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getSoundInfo(swigCPtr, this, key, FMOD_STUDIO_SOUND_INFO.getCPtr(info), info));
  }

  public FMOD_RESULT lookupID(String path, FMOD_GUID id) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_lookupID(swigCPtr, this, path, FMOD_GUID.getCPtr(id), id));
  }

  public FMOD_RESULT lookupPath(FMOD_GUID id, String path, int size, SWIGTYPE_p_int retrieved) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_lookupPath(swigCPtr, this, FMOD_GUID.getCPtr(id), id, path, size, SWIGTYPE_p_int.getCPtr(retrieved)));
  }

  public FMOD_RESULT getListenerAttributes(FMOD_3D_ATTRIBUTES attributes) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getListenerAttributes(swigCPtr, this, FMOD_3D_ATTRIBUTES.getCPtr(attributes), attributes));
  }

  public FMOD_RESULT setListenerAttributes(FMOD_3D_ATTRIBUTES attributes) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_setListenerAttributes(swigCPtr, this, FMOD_3D_ATTRIBUTES.getCPtr(attributes), attributes));
  }

  public FMOD_RESULT loadBankFile(String filename, long flags, Bank bank) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_loadBankFile(swigCPtr, this, filename, flags, bank));
  }

  public FMOD_RESULT loadBankMemory(String buffer, int length, FMOD_STUDIO_LOAD_MEMORY_MODE mode, long flags, Bank bank) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_loadBankMemory(swigCPtr, this, buffer, length, mode.swigValue(), flags, bank));
  }

  public FMOD_RESULT loadBankCustom(FMOD_STUDIO_BANK_INFO info, long flags, Bank bank) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_loadBankCustom(swigCPtr, this, FMOD_STUDIO_BANK_INFO.getCPtr(info), info, flags, bank));
  }

  public FMOD_RESULT unloadAll() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_unloadAll(swigCPtr, this));
  }

  public FMOD_RESULT getCPUUsage(FMOD_STUDIO_CPU_USAGE usage) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getCPUUsage(swigCPtr, this, FMOD_STUDIO_CPU_USAGE.getCPtr(usage), usage));
  }

  public FMOD_RESULT getBufferUsage(FMOD_STUDIO_BUFFER_USAGE usage) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getBufferUsage(swigCPtr, this, FMOD_STUDIO_BUFFER_USAGE.getCPtr(usage), usage));
  }

  public FMOD_RESULT resetBufferUsage() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_resetBufferUsage(swigCPtr, this));
  }

  public FMOD_RESULT registerPlugin(SWIGTYPE_p_FMOD_DSP_DESCRIPTION description) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_registerPlugin(swigCPtr, this, SWIGTYPE_p_FMOD_DSP_DESCRIPTION.getCPtr(description)));
  }

  public FMOD_RESULT unregisterPlugin(String name) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_unregisterPlugin(swigCPtr, this, name));
  }

  public FMOD_RESULT getBankCount(SWIGTYPE_p_int count) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getBankCount(swigCPtr, this, SWIGTYPE_p_int.getCPtr(count)));
  }

  public FMOD_RESULT getBankList(Bank array, int capacity, SWIGTYPE_p_int count) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getBankList(swigCPtr, this, array, capacity, SWIGTYPE_p_int.getCPtr(count)));
  }

  public FMOD_RESULT flushCommands() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_flushCommands(swigCPtr, this));
  }

  public FMOD_RESULT startRecordCommands(String filename, long flags) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_startRecordCommands(swigCPtr, this, filename, flags));
  }

  public FMOD_RESULT stopRecordCommands() {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_stopRecordCommands(swigCPtr, this));
  }

  public FMOD_RESULT playbackCommands(String filename) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_playbackCommands(swigCPtr, this, filename));
  }

  public FMOD_RESULT setCallback(SWIGTYPE_p_f_p_FMOD_STUDIO_SYSTEM_unsigned_int_p_void_p_void__FMOD_RESULT callback, long callbackmask) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_setCallback__SWIG_0(swigCPtr, this, SWIGTYPE_p_f_p_FMOD_STUDIO_SYSTEM_unsigned_int_p_void_p_void__FMOD_RESULT.getCPtr(callback), callbackmask));
  }

  public FMOD_RESULT setCallback(SWIGTYPE_p_f_p_FMOD_STUDIO_SYSTEM_unsigned_int_p_void_p_void__FMOD_RESULT callback) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_setCallback__SWIG_1(swigCPtr, this, SWIGTYPE_p_f_p_FMOD_STUDIO_SYSTEM_unsigned_int_p_void_p_void__FMOD_RESULT.getCPtr(callback)));
  }

  public FMOD_RESULT getUserData(SWIGTYPE_p_p_void userData) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_getUserData(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(userData)));
  }

  public FMOD_RESULT setUserData(SWIGTYPE_p_void userData) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.System_setUserData(swigCPtr, this, SWIGTYPE_p_void.getCPtr(userData)));
  }

}
