/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fmod;

public class VCA {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VCA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VCA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javafmodJNI.delete_VCA(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean isValid() {
    return javafmodJNI.VCA_isValid(swigCPtr, this);
  }

  public FMOD_RESULT getID(FMOD_GUID id) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.VCA_getID(swigCPtr, this, FMOD_GUID.getCPtr(id), id));
  }

  public FMOD_RESULT getPath(String path, int size, SWIGTYPE_p_int retrieved) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.VCA_getPath(swigCPtr, this, path, size, SWIGTYPE_p_int.getCPtr(retrieved)));
  }

  public FMOD_RESULT getFaderLevel(SWIGTYPE_p_float level) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.VCA_getFaderLevel(swigCPtr, this, SWIGTYPE_p_float.getCPtr(level)));
  }

  public FMOD_RESULT setFaderLevel(float level) {
    return FMOD_RESULT.swigToEnum(javafmodJNI.VCA_setFaderLevel(swigCPtr, this, level));
  }

}
